# Generated by Django 3.1.5 on 2021-04-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20210402_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_month',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_year',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
