# Generated by Django 3.1.5 on 2021-04-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20210427_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_year',
            field=models.IntegerField(),
        ),
    ]
