# Generated by Django 3.1.5 on 2021-05-04 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20210427_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='billing_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='billing.billingprofile'),
        ),
    ]
