# Generated by Django 3.2.5 on 2021-08-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='created_user',
        ),
    ]
