# Generated by Django 3.1.5 on 2021-05-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210504_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserVery',
            new_name='UserVerify',
        ),
    ]
