# Generated by Django 3.2.5 on 2021-08-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_user_profile_created_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
