# Generated by Django 3.1.5 on 2021-05-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210505_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverify',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
