# Generated by Django 3.2.5 on 2021-08-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
