# Generated by Django 3.2.5 on 2021-08-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_profile_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, default=1, max_length=150),
            preserve_default=False,
        ),
    ]
