# Generated by Django 3.2.5 on 2021-08-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210811_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_email',
            field=models.EmailField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
