# Generated by Django 3.2.5 on 2021-08-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_profile_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
