# Generated by Django 3.2.5 on 2021-08-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_auto_20210806_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='courier_price',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='courier',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
