# Generated by Django 3.2.5 on 2021-08-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_auto_20210806_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='total',
            new_name='order_end_total',
        ),
    ]
