# Generated by Django 3.2.5 on 2021-08-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_rename_total_courier_order_end_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='status',
            field=models.CharField(blank=True, choices=[('ÇATDIRILDI', 'ÇATDIRILDI'), ('YOLDADIR', 'YOLDADIR')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courier.courier')),
            ],
        ),
    ]
