# Generated by Django 3.2.5 on 2021-08-04 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_room_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
        ),
    ]
